gtk-rs/examples

src/cairotest.rs
src/text_viewer.rs

cc https://github.com/rust-gnome/gtk/issues/42

Avoid using FromPrimitive and PI_2

---

Cargo.toml
src/gtktest.rs
src/notebook.rs

Let's see if Appveyor picks this up

Restore gtktest

---

src/sync_widgets.rs

See https://github.com/rust-gnome/gtk/pull/114

Use correct name for "set_homogeneous" following upstream change

---

.travis.yml
Cargo.toml
appveyor.yml
src/cairo_threads.rs

I'm favoring correctness over performance here. This could probably be done less safely but more efficiently.

Add cairo_threads -- my attempt at multi-threaded drawing

---

Cargo.toml
src/multithreading_context.rs

Added an example of multithreaded program that uses thread local storage key.

Added an example of multithreaded program

---

.travis.yml
src/treeview.rs

after https://github.com/gtk-rs/glib/pull/75

Fix the build after Value methods becoming unsafe

---

src/basic.rs
src/builder_basics.rs
src/cairo_threads.rs
src/cairotest.rs
src/gtktest.rs
src/multithreading_context.rs
src/notebook.rs
src/sync_widgets.rs
src/text_viewer.rs
src/treeview.rs

Fixes breaking changes introduced in https://github.com/gtk-rs/gtk/pull/221

Object reform fallout fixes

---

src/treeview.rs

Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

treeview: get_selected returns a model, rename the variable to reflect this

---

Cargo.toml
src/cairo_threads.rs
src/multithreading_context.rs
src/treeview.rs

Depend on gdk-pixbuf and use Duration

---

Cargo.toml
src/simple_treeview.rs

Add more simple treeview example

---

src/treeview.rs

For good build of https://github.com/gtk-rs/gtk/pull/279

Fix call TreeModel.get_path

---

src/treeview.rs

This kind of is a public-facing branch so let's do this by the book not by force-pushing.

Revert "Fix call TreeModel.get_path"

---

src/cairo_threads.rs

Fix breakage after https://github.com/gtk-rs/cairo/pull/75

Adjust to ImageSurface::get_data change

---

Cargo.toml
appveyor.yml
src/notebook.rs

Part of https://github.com/gtk-rs/gir-files/issues/1
WIP just features template

Gir files zesty

---

Cargo.toml
src/grid.glade
src/grid.rs

Example for grid child properties https://github.com/gtk-rs/gtk/pull/395

Add grid example

---

src/grid.rs

Preparation for merging https://github.com/gtk-rs/gtk/pull/416.
Normal that it fails.

Rename grid child properties to "cell"

---

src/notebook.rs

Fix after apply https://github.com/gtk-rs/gir/pull/305

Use set_focus_on_click without concrete trait

---

src/notebook.rs

Prerequisite of https://github.com/gtk-rs/gtk/pull/446
Normally that build fails

Prepare for `Into<Option<&str>>`

---

Cargo.toml

Continue of https://github.com/gtk-rs/examples/pull/112
@GuillaumeGomez  this mail
I ping you when CI finished

Replace to main crates

---

Cargo.toml

Doing it manually as there I can redo only last of 2 PRs
Part of https://github.com/gtk-rs/gtk/issues/465

Revert Cargo.toml to version before `replace`

---

src/gtktest.rs

Fixes build of https://github.com/gtk-rs/gdk/pull/147

Use generated ModifierType

---

CONTRIBUTING.md

To make the github rendering more attractive.

Add some spaces

---

src/bin/multi_windows.rs

Add multi window example

---

Cargo.toml
src/bin/gtktest.rs

Example right way to watch about gtk::Switch changes. See https://github.com/gtk-rs/gtk/pull/491, https://github.com/gtk-rs/gtk/pull/492

Add use of gtk::Switch::connect_changed_active

---

src/bin/child-properties.rs

This is based on this [pull request](https://github.com/gtk-rs/gtk/pull/481).

Add example for child properties

---

.gitignore
src/bin/drag_and_drop.rs

Still includes debugging output, this will be removed in final commit.
This is the same as #116 but pushes to the `pending` branch instead.

Add simple drag and drop example

---

Cargo.toml
src/bin/pango_attributes.rs

Add example for pango text attributes

---

Cargo.toml
src/bin/cairo_png.rs
src/bin/treeview.rs

cc @GuillaumeGomez, MGageMorgan

Added example for `ImageSurface::write_to_png`

---

build.sh
src/bin/grid.rs

Attempt to fix memory kills in travis

Travis fix

---

src/bin/drag_and_drop.rs

Small fix for https://github.com/gtk-rs/gtk/pull/546
Currently build fails.
cc @GuillaumeGomez

Fix set_text usage

---

src/bin/cairo_png.rs
src/bin/cairo_threads.rs

See https://github.com/gtk-rs/cairo/pull/146

Use new cairo surfaces API

---

Cargo.toml
build.sh
src/bin/builder_basics.rs
src/bin/cairo_png.rs
src/bin/cairo_threads.rs
src/bin/child-properties.rs
src/bin/drag_and_drop.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/multithreading_context.rs
src/bin/notebook.rs
src/bin/pango_attributes.rs
src/bin/simple_treeview.rs
src/bin/sync_widgets.rs
src/bin/text_viewer.rs
src/bin/treeview.rs

For new release
cc @GuillaumeGomez

Merge pending to master

---

src/bin/transparent_main_window.rs

Add example how to make the main window transparent

---

Cargo.toml
src/bin/drag_and_drop.rs
src/bin/gtktest.rs
src/bin/treeview.rs

Part of https://github.com/gtk-rs/gir/issues/468
Don't builds until gtk, gdk, ~sys~ regened with https://github.com/gtk-rs/gir/pull/471
cc @GuillaumeGomez , @sdroege
EDIT: sys don't need updated for this PR works.

Fix flags values

---

Cargo.toml
src/bin/basic.rs
src/bin/builder_basics.glade
src/bin/builder_basics.rs
src/bin/cairo_threads.rs
src/bin/cairotest.rs
src/bin/child-properties.rs
src/bin/drag_and_drop.rs
src/bin/grid.glade
src/bin/grid.rs
src/bin/gtktest.glade
src/bin/gtktest.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/multithreading_context.rs
src/bin/notebook.rs
src/bin/pango_attributes.rs
src/bin/simple_treeview.rs
src/bin/sync_widgets.glade
src/bin/sync_widgets.rs
src/bin/text_viewer.glade
src/bin/text_viewer.rs
src/bin/transparent_main_window.rs
src/bin/treeview.rs

Application

---

Cargo.toml
build_travis.sh
src/bin/gio_futures.rs

Depends on https://github.com/gtk-rs/gio/pull/108
I'd also like to add an example using async/await but that would require nightly. How would we handle that?

Add gio_futures example

---

Cargo.toml
build_travis.sh
src/bin/gio_futures_await.rs

This depends on https://github.com/gtk-rs/glib/pull/325 and is on top of https://github.com/gtk-rs/examples/pull/166

Add async/await GIO example

---

build_travis.sh

Fix takes too long with no estimate
cc @GuillaumeGomez, @sdroege

Don't test futures-nightly feature

---

.travis.yml
Cargo.toml
build_travis.sh

@GuillaumeGomez maybe gtk-bootstrap better moved to gtk-rs
cc @sdroege

Add gtk 3.22.30 to travis

---

Cargo.toml
build_travis.sh

Part of https://github.com/gtk-rs/examples/pull/173
cc @GuillaumeGomez, @sdroege

Use gtk/v3_22_30

---

src/bin/basic.rs
src/bin/builder_basics.rs
src/bin/cairo_threads.rs
src/bin/cairotest.rs
src/bin/child-properties.rs
src/bin/clock.rs
src/bin/drag_and_drop.rs
src/bin/drag_and_drop_textview.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/multithreading_context.rs
src/bin/notebook.rs
src/bin/pango_attributes.rs
src/bin/simple_treeview.rs
src/bin/sync_widgets.rs
src/bin/text_viewer.rs
src/bin/treeview.rs

Improve code, remove clone when unnecessary

---

src/bin/cairo_threads.rs
src/bin/child-properties.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/notebook.rs
src/bin/text_viewer.rs
src/bin/treeview.rs

Fixes https://github.com/gtk-rs/examples/issues/179

Fix various reference cycles in the examples

---

src/bin/status_icon.rs

We'll need to wait for https://github.com/gtk-rs/gtk/pull/714 to be merged first as a last check.

Update to gtk

---

src/bin/basic.rs
src/bin/builder_basics.rs
src/bin/cairo_threads.rs
src/bin/cairotest.rs
src/bin/child-properties.rs
src/bin/clock.rs
src/bin/drag_and_drop.rs
src/bin/drag_and_drop_textview.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/multithreading_context.rs
src/bin/notebook.rs
src/bin/pango_attributes.rs
src/bin/simple_treeview.rs
src/bin/status_icon.rs
src/bin/sync_widgets.rs
src/bin/text_viewer.rs
src/bin/transparent_main_window.rs
src/bin/treeview.rs

Fixes problem described in https://github.com/gtk-rs/gtk/pull/731/files#r228063962
Also see https://wiki.gnome.org/HowDoI/GtkApplication,
https://developer.gnome.org/gtk3/stable/gtk-getting-started.html
https://gitlab.gnome.org/GNOME/gtk/blob/master/examples/bp/bloatpad.c
cc @GuillaumeGomez , @sdroege

Change event for application to build its UI

---

Cargo.toml
src/bin/overlay.rs

Add overlay example

---

Cargo.toml
src/bin/listbox_model.rs

This currently is patched to use my personal glib branch.
See https://github.com/gtk-rs/glib/pull/392

Port to the new subclassing infrastructure from the glib bindings

---

src/bin/cairotest.rs
src/bin/transparent_main_window.rs

Part of https://github.com/gtk-rs/cairo/pull/217
cc @GuillaumeGomez , @sdroege

Use reexported cairo enums

---

Cargo.toml
src/bin/listbox_model.rs

And for glib_wrapper! not requiring anything special in scope anymore.

Update listbox_model example for glib_object_get_type! macro removal

---

src/bin/accessibility.rs
src/bin/child-properties.rs

Part of https://github.com/gtk-rs/glib/pull/389.
cc @GuillaumeGomez, @sdroege, @philn

Prepare for glib::gstring::GString

---

build_travis.sh

Revert "Add target builds"

---

Cargo.toml
src/bin/css.rs
src/bin/tree_model_sort.rs

Add TreeModelSort And CSS examples

---

src/bin/builder_basics.rs
src/bin/grid.rs
src/bin/gtktest.rs

Remove checking for gtk_3_10

---

CONTRIBUTING.md

Remove CONTRIBUTING.md

---

.travis.yml
Cargo.toml
src/bin/gtktest.rs

Remove unneeded dependence

---

src/bin/accessibility.rs
src/bin/basic.rs
src/bin/builder_basics.rs
src/bin/cairo_threads.rs
src/bin/cairotest.rs
src/bin/child-properties.rs
src/bin/clock.rs
src/bin/css.rs
src/bin/drag_and_drop.rs
src/bin/drag_and_drop_textview.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/list_store.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/multithreading_context.rs
src/bin/notebook.rs
src/bin/overlay.rs
src/bin/pango_attributes.rs
src/bin/progress_tracker.rs
src/bin/simple_treeview.rs
src/bin/sync_widgets.rs
src/bin/text_viewer.rs
src/bin/transparent_main_window.rs
src/bin/tree_model_sort.rs
src/bin/treeview.rs

cc @EPashkin @sdroege 
It's very likely that I missed some. Future will tell us. :)

no more into

---

src/bin/css.rs
src/bin/grid.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/multi_windows.rs
src/bin/notebook.rs
src/bin/overlay.rs
src/bin/pango_attributes.rs
src/bin/progress_tracker.rs
src/bin/sync_widgets.rs
src/bin/text_viewer.rs
src/bin/transparent_main_window.rs

Finish adding Some

---

src/bin/transparent_main_window.rs

See https://github.com/gtk-rs/gir/pull/780
----
This will fail until https://github.com/gtk-rs/gtk/pull/816 is merged

Fix build after &Option<T> -> Option<&T> change

---

Cargo.toml
src/bin/entry_completion.rs

I spend some fun trying to figure out how the autocompletion of a field work. I thought to build a basic example. Make sense?
Can you help me improve this example?
Thanks!

Add an EntryCompletion example

---

.travis.yml
src/bin/cairo_threads.rs

Follow-up of gtk-rs/cairo#260
cc @EPashkin @sdroege

Up to cairo

---

Cargo.toml

@EPashkin With this commit, next update shouldn't silently update dependencies without me noticing. :)

Use crates.io instead of git

---

Cargo.toml
src/bin/builder_signal.glade
src/bin/builder_signal.rs

__Requires__ gtk-rs/gtk#852.
cc @EPashkin @GuillaumeGomez @sdroege

Add example builder_signal

---

.travis.yml

We forgot to update it here as well. :smile: 
cc @EPashkin @sdroege

Update minimum rust version

---

Cargo.toml
build_travis.sh

Part of https://github.com/gtk-rs/gtk/issues/887
This should be the last one! Then we can go. :)

remove subclassing feature

---

src/bin/tree_model_sort.rs

Depending on the discussion in https://github.com/gtk-rs/gio/pull/250, we might not want to merge this PR...

Prelude import

---

src/bin/clock.rs
src/bin/entry_completion.rs
src/bin/list_store.rs
src/bin/menu_bar_system.rs
src/bin/progress_tracker.rs
src/bin/tree_model_sort.rs

@GuillaumeGomez 
Part of gtk-rs/sys#152.

Fix build of the examples

---

.travis.yml
src/bin/multi_windows.rs
src/bin/notebook.rs
src/bin/progress_tracker.rs
src/bin/treeview.rs

Cleanup clone

---

Cargo.toml
src/bin/drag_and_drop_textview.rs

And handle non-local URLs correctly too.

Drop url crate dependency and use gio::File instead

---

.gitignore
Cargo.toml
src/bin/iconview_example.rs

Re-opening, added more comments and ran cargo fmt.

Icon View example

---

src/bin/builder_basics.rs
src/bin/builder_signal.rs
src/bin/gtktest.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/printing.rs
src/bin/text_viewer.rs
src/bin/treeview.rs

Recursive main loops can cause interesting reentrancy issues with e.g.
mutexes or refcells and are generally not a good idea.
See also https://github.com/gtk-rs/gtk/issues/952.
----
CC @sprang

Don't use recursive main loops for the dialogs

---

.travis.yml
build_travis.sh

Copy of #283 
!!!Please do not merge this until fixes for gio, gdk, gtk and maybe https://github.com/gtk-rs/glib/pull/579 are published and CI passed here
cc @GuillaumeGomez, @sdroege

Test osx on master

---

src/bin/clipboard_simple.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/menu_bar.rs
src/bin/menu_bar_system.rs
src/bin/progress_tracker.rs
src/bin/text_viewer.rs
src/bin/treeview.rs

Part of https://github.com/gtk-rs/gtk/pull/958
cc @EPashkin @sdroege

Replace destroy calls with close

---

src/bin/basic_subclass.rs

Part of https://github.com/gtk-rs/gio/pull/284
cc @GuillaumeGomez , @sdroege

Fix use from prelude

---

.travis.yml
src/bin/accessibility.rs
src/bin/child-properties.rs
src/bin/gtktest.rs
src/bin/listbox_model.rs
src/bin/printing.rs

Fix examples with get_text()

---

src/bin/basic_subclass.rs
src/bin/listbox_model.rs

Update for removal of ObjectImpl::get_type_data()

---

src/bin/clock.rs

In order to fix https://github.com/gtk-rs/gtk/pull/1048

Update function reference

---

src/bin/list_store.rs
src/bin/progress_tracker.rs

Linked to https://github.com/gtk-rs/glib/pull/693

Update to new timeout_* API

---

src/bin/basic_subclass.rs
src/bin/listbox_model.rs

Subclass cleanup
