- src/notebook.rs
Capturing the index by value does only work if tabs are added and removed in LIFO order.
Depends on https://github.com/rust-gnome/gtk/pull/73
I'm not quite sure about the `'static` bound on `Widget`, but I hope it's ok..
> Use correct tab indexes in signal handler

- Cargo.toml
- README.md
- builder_basics.glade
- src/builder_basics.rs
I was playing with the `Builder` widget but could not make it work.
I decided to write a basic example so someone could help me fix what is going on and eventually add it to the example repo.
If you run `cargo build` you should see the following error:
```rust
src/builder_basics.rs:15:5: 15:22 error: the type of this value must be known in this context
src/builder_basics.rs:15     window.show_all();
^~~~~~~~~~~~~~~~~
```
The glade file is taken from a [Python GTK tutorial](https://python-gtk-3-tutorial.readthedocs.org/en/latest/builder.html).
If we make this work, I should be able to add 1 or 2 examples showing how to use the builder.
Tell me what you think. :smile:
> Add a builder example to show the basics

- Cargo.toml
The examples still need features internally to remain buildable with older libraries.
> Stop using gtk crate features

- src/cairotest.rs
- src/gtktest.rs
Objects are passed to handlers by reference now.
The first parameter type is the same as the type, `connect_*` was called on.
> Signals API adjustment

- Cargo.toml
IMHO `gtk_3_18` feature better changed to `gtk_3_16` for consistency
Also `defaults` commented as example
> Fix building with upper gtk versions

- src/gtktest.rs
WIP.
Example using https://developer.gnome.org/gtk3/stable/GtkSpinButton.html#GtkSpinButton-input after https://github.com/gtk-rs/gtk/pull/317
Seems returning  `GTK_INPUT_ERROR` still applied `new_value` (don't changing it equals `new_value = 0.;`), then not sure that we need it.
cc @gkoz 
Edit: `GTK_INPUT_ERROR` working normal and it depends of `update_policy`.
This old code for future reference
```rust
Ok(value) if value >= 99. => {
println!("circular");
*new_value = 10.;
Err(()) //Not working
}
```
> Spin button signals

- Cargo.toml
- appveyor.yml
- src/notebook.rs
Part of https://github.com/gtk-rs/gir-files/issues/1
> Merge pending into master

- Cargo.toml
This seems allow use crated `Cargo.toml` in master branch (https://github.com/EPashkin/gtk/blob/master/Cargo.toml) and remove need in `crate` branch at all.
Works well with `.cargo/config/path` overrides. Ex. my local version with https://github.com/gtk-rs/gdk/pull/140 and https://github.com/gtk-rs/gtk/pull/462 rebased on my master produces only 2 equal warnings (dependency really added in gdk's PR)
```
warning: path override for crate `gdk` has altered the original list of
dependencies; the dependency on `gobject-sys` was either added or
modified to not match the previously resolved version
```
with one `warning: package replacement is not used: https://github.com/rust-lang/crates.io-index#gdk:0.5.2
` per replaced crate in `.cargo/config/path`
⚠️ WIP. Currently linked to my forks of …
> Use crates with git replacements in `pending` branch

- Cargo.toml
- src/bin/clock.rs
- src/bin/sync_widgets.rs
How to make a minimal clock with gtk-rs + chrono only.
I had to use this code in a personal project, and IMO it could save someone new 2 minutes to have this example.
The gtk code is adapted from basic.rs but with a Label instead of a Button.
> using chrono and gtk::timeout_add_seconds to build a basic clock

- Cargo.toml
- src/bin/drag_and_drop_textview.rs
This example appears to work correctly for me now. I think this was resolved by fixing internal list structures are some point, so I wanted to get this queued up for merging. This requires a new dependency, but hopefully that's not an issue.
This is something that applications likely want to do (like one I'm working on) which is why I created this example in the first place. So I think it'd be helpful to other devs in addition to the basic drag-and-drop example.
> Add URL list drag and drop example

- src/bin/gtktest.glade
Fix double activating found thanks to https://github.com/gtk-rs/examples/issues/162
We already have activating in code:
```rust
let spinner: Spinner = builder.get_object("spinner").expect("Couldn't get spinner");
spinner.start();
```
cc @GuillaumeGomez
> Disable spinner in glade file, to make starting it in code meaningful

- src/bin/gio_futures.rs
- src/bin/gio_futures_await.rs
Depends on https://github.com/gtk-rs/glib/pull/328
> Don't require a mutable main context in the futures examples

- src/bin/gio_futures_await.rs
And directly call println!() as the bug in rustc is fixed now.
> Add proc_macro_non_items feature as required by latest nightly

- Cargo.toml
- src/bin/gio_futures.rs
The futures crates were janked from crates.io and renamed to
futures-preview for whatever reason.
Nightly still does not compile because `futures-core-preview` does not compile
> Use futures-preview crates instead of futures

- Cargo.toml
- src/bin/menu_bar.rs
- src/bin/menu_bar_system.rs
"Accelerator" is the term GTK uses for keyboard shortcuts such as `Ctrl+Q`. The shortcuts get displayed for items in a menu, which seems to make these two examples the best for also demonstrating accelerators.
> Add accelerators to menu examples

- Cargo.toml
- build_travis.sh
futures 0.2 is not maintained any longer and the nightly parts don't
build with the latest nightly toolchain anymore.
> Remove futures-nightly from travis

- Cargo.toml
@GuillaumeGomez PR in high-probable case that https://github.com/gtk-rs/glib/pull/373 fails again
cc @sdroege
> Finish feature "futures-nightly" removal

- Cargo.toml
- src/bin/accessibility.rs
> Add atk/accessibility example

- src/bin/cairo_threads.rs
cc @GuillaumeGomez, @sdroege 
Error on rust 1.28.0 in https://github.com/gtk-rs/gio/pull/185
```
error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
--> src/bin/cairo_threads.rs:143:32
|
143 |     let (ready_tx, ready_rx) = glib::MainContext::channel(glib::PRIORITY_DEFAULT);
|                                ^^^^
```
> Add missing extra crate

- .travis.yml
- Cargo.toml
- build_travis.sh
@EPashkin Can you upload a 3.24 version of the GTK bundle for travis? Until that is there this will fail :)
@GuillaumeGomez Is there any reason why we don't use docker images of reasonable well up to date Linux distros for the CI?
> Update minimum versions and add 3.24 to the travis CI

- Cargo.toml
- src/bin/progress_tracker.rs
Adds example with a progress bar that's updated over time after clicking on a button. The button spawns a thread that sends an event each second through a channel to a `gtk::idle_add` that periodically checks for values.
Adds the cascade crate since it makes constructing GTK widgets simpler.
Closes #209
> Add progress-tracker example

- Cargo.toml
- build_travis.sh
- src/bin/gio_futures.rs
- src/bin/gio_futures_await.rs
While this requires nightly, the API is now stabilized and will become part of Rust 1.36. IMHO we should merge this now so that it can all get wider testing.
This is currently marked as WIP because it uses https://github.com/gtk-rs/glib/pull/476 and https://github.com/gtk-rs/gir/pull/753 via Cargo patching
> Port to futures 0.3

- Cargo.toml
- src/bin/clipboard_simple.rs
Ported from https://developer.gnome.org/gtkmm-tutorial/stable/sec-clipboard-examples.html.en
Current implementation works, but is blocking on gtk-rs/gtk#478 and gtk-rs/gdk#148 which are soon to be merged.
There is additional functionality that is blocking on gtk-rs/gtk#479, which hasn't been started, but it's commented out.
> Add simple clipboard example

- src/bin/list_store.rs
- src/bin/listbox_model.rs
- src/bin/simple_treeview.rs
... in consequence of gtk-rs/glib#513
For the `Result<_, _>::expect` behaviour, please see the following discussion: https://github.com/gtk-rs/gir/pull/825#pullrequestreview-272474063. TLDR: the argument for `expect` should refer to the context (or the reason why it shouldn't panic), the error will be automatically added in the panic message (using the `Debug` trait unfortunately).
For the method names, please see: https://github.com/gtk-rs/glib/pull/513#pullrequestreview-271892055 and then https://github.com/gtk-rs/glib/pull/513#issuecomment-519547950. TLDR: `get` allows writing generic code, `get_some` is the best name we could think of to `get` the actual value for a non-optional `Type` without the need to `unwrap` an `Ok` output of `get`.
> Update for new `glib::Value::get` signature

- src/bin/menu_bar_system.rs
triple slashes are used for function documentation.
`set_author` is called twice. I assume this is not needed
> Minor fix in menu_bar_system

- Cargo.toml
- src/bin/printing.glade
- src/bin/printing.rs
For work I was doing a small GTK app that took some input and printed it. I was doing it in Rust with gtk-rs and, sadly, I didn't find much about how to do the printing part.
After a while looking at the GTK and gtk-rs docs and with the help of some IRC users I figured out how to do it.
After managing to do it, they suggested me to make a sample to add to this repo, so here it is.
This sample has a window with a header bar and three items: 2 Entry fields and a Button. Clicking the button starts up the print dialog with the contents of the Entry fields.
I also added the pangocairo crate, which is basically only used to render the pango Paragraph with `show_layout()`.
> Add Printing sample

- src/bin/cairo_threads.rs
- src/bin/child-properties.rs
- src/bin/clipboard_simple.rs
- src/bin/clone_macro.rs
- src/bin/entry_completion.rs
- src/bin/grid.rs
- src/bin/gtktest.rs
- src/bin/listbox_model.rs
- src/bin/menu_bar.rs
- src/bin/menu_bar_system.rs
- src/bin/multi_windows.rs
- src/bin/notebook.rs
- src/bin/printing.rs
- src/bin/progress_tracker.rs
- src/bin/text_viewer.rs
- src/bin/treeview.rs
So we currently have a few issues with the `clone` macro: since it only allows idents, it cannot take input like `x.y` or even `*x`. Updating to `expr` would be enough I guess but not sure if that will be this simple. :3
cc @EPashkin @sdroege @antoyo
> Clone macro

- Cargo.toml
The gtk-rs examples fail to compile because multiple examples make use of once_cell, but there is no dependency on once_cell in Cargo.toml.
```
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
--> src/bin/basic_subclass.rs:13:1
|
13 | extern crate once_cell;
| ^^^^^^^^^^^^^^^^^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/27812
```
> Add dependency on once_cell to Cargo.toml

- .travis.yml
- build_travis.sh
@GuillaumeGomez, @sdroege I added 2 tests for OSX
and changed `cargo check` to `cargo build` in usual cases to detect link errors.
Note that travis just add it to usual 4x4 tests
We have https://github.com/gtk-rs/gtk/issues/935#issuecomment-578448919 and 
https://github.com/gtk-rs/gio/issues/272 that shows that no gio::DesktopAppInfo, gtk::Plug and gtk::Socket on macos.
First will be fixed in https://github.com/gtk-rs/gio/pull/273 (or I re-add it tomorrow).
Gtk will be fixed in https://github.com/gtk-rs/gtk/pull/944.
> Add osx test on travis

- build_travis.sh
See https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
cc @GuillaumeGomez, @sdroege
> Prevent osx build failure

- src/bin/clone_macro.rs
I'll then backport this on the pending branch. Fixes #293.
Full explanations: the `state2` variable needs to be cloned otherwise it won't exist anymore, which will prevent the closure to be actually "called" (it'll return early).
> Fix clone_macro example

- src/bin/basic_subclass.rs
> basic_subclass: fix name of our GObject subclasss type
